mysql:
    image: mysql:5.7.11
    environment:
        - MYSQL_ROOT_PASSWORD=root
php :
    image: php:7.2-apache
    ports:
        - "80:80"
    volumes:
        - ../src:/var/www/html
    links:
        - mysql:db